# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/22b4a32a-0957-4f09-ad8a-8c93d1f81bf0";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };
  boot.initrd.luks.devices."crypt_root".device =
    "/dev/disk/by-uuid/39513a8b-1bd1-4068-af30-411fce930fa4";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/22b4a32a-0957-4f09-ad8a-8c93d1f81bf0";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/19C9-925B";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/22b4a32a-0957-4f09-ad8a-8c93d1f81bf0";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "noatime"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/12e10166-b0fb-4ace-a50d-8d2613a0240b"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
