{
  pkgs,
  lib,
  inputs,
  ...
}:
{
  imports = [
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
    inputs.niri.homeModules.niri

    ./keybindings.nix
    #./hypridle.nix
    ./mako.nix
  ];

  home.packages = with pkgs; [
    libnotify # 提供 notify-send 命令
    wlr-randr # 用于调整显示器设置
  ];
  programs.dank-material-shell = {
    enable = true;
    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.

      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab" # Please note that niri will throw an error if any of these files are missing.
        "binds"
        "colors"
        "layout"
        "outputs"
        "wpblur"
      ];
    };

    systemd = {
      enable = true; # Systemd service for auto-start
      restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
    };
  };
  programs.niri.enable = true;
  programs.niri.package = pkgs.niri;

  /*
      # hypridle 配置
      services.hypridle.enable = true;
  */

  # 通知设置
  services.mako.enable = true;

  programs.niri.settings = {
    xwayland-satellite.path = lib.getExe pkgs.xwayland-satellite;

    spawn-at-startup = [
      { command = [ "wezterm" ]; }
    ];

    # https://github.com/YaLTeR/niri/wiki/Configuration:-Input
    input.keyboard.numlock = true;
    input.focus-follows-mouse.enable = true;
    # https://github.com/YaLTeR/niri/wiki/Configuration:-Layout
    layout = {
      gaps = lib.mkForce 12;
      center-focused-column = "on-overflow";

      preset-column-widths = [
        { proportion = 1. / 3.; }
        { proportion = 1. / 2.; }
        { proportion = 2. / 3.; }
        { proportion = 1.; }
      ];
      preset-window-heights = [
        { proportion = 1. / 3.; }
        { proportion = 1. / 2.; }
        { proportion = 2. / 3.; }
        { proportion = 1.; }
      ];
      default-column-width.proportion = lib.mkForce (1. / 2.);
    };

    prefer-no-csd = true;

    window-rules = [
      {
        clip-to-geometry = true;
        geometry-corner-radius = {
          top-left = 16.0;
          top-right = 16.0;
          bottom-left = 16.0;
          bottom-right = 16.0;
        };
      }
      {
        matches = [ { app-id = "^org\.wezfurlong\.wezterm$"; } ];
        default-column-width = { };
      }
      {
        matches = [
          {
            app-id = "firefox$";
            title = "^Picture-in-Picture$";
          }
        ];
        open-floating = true;
      }
    ];
  };

}
